import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import Logo from "../assets/logos/Logo.png";
import LogoText from "../assets/logos/LogoText.png";
import OpLogo from "../assets/logos/optimism-ethereum-op-logo.png";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen flex flex-row justify-start items-center">
        <div className="flex flex-row justify-center items-center absolute top-4 left-8">
          <span className="font-guava text-[1.5rem]">Powered By</span>
          <Image
            alt="Optimism Logo"
            src={OpLogo}
            className="ml-4"
            height={50}
          ></Image>
        </div>
        <div className="flex flex-row justify-start items-center ml-20">
          <Image alt="logo" src={Logo} height={400} className="ml-20"></Image>
          <div className="h-[70%] w-[50%] flex flex-col justify-start items-center ml-28">
            <Image alt="logo" src={LogoText} height={200}></Image>
            <span className="text-[3rem] font-guava text-center">
              Paint The Canvas to Rule
            </span>
            <span className="text-[1.3rem] font-gunplay text-center mt-6">
              Come and pay to paint the canvas, the more squares you color the
              larger bounty you win. Web3 place is a fun time-based game in
              which you have to rule the canvas by colouring it.
            </span>
            <button
              className="button flex flex-row justify-center items-center font-guava cursor-pointer bg-[#d0d408] w-[14rem] h-[3.5rem] mt-12 text-[1.5rem]"
              onClick={() => {
                router.push("/Home");
              }}
            >
              Enter Dapp
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
